# Dockerfile configuration
# https://docs.docker.com/engine/reference/builder/

# Last modified: 2021-09-25 23:10:29

FROM mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu

# Create user for the GitHub-hosted runner
RUN useradd --create-home runner
