# Dockerfile configuration
# https://docs.docker.com/engine/reference/builder/

# Pin the VS Code Ubuntu version to match the GitHub Ubuntu version
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-21.04
