# Dockerfile configuration
# https://docs.docker.com/engine/reference/builder/

# Keep this pinned to `gh/brew` so it's possible to continue using Homebrew and
# and other package managers to configure the `gh/brew/devtools` image
FROM ghcr.io/bottle-garden/vscode/gh/brew:main
